version: "3.9"

services:
  bot:
    container_name: nft-wizard-bot
    image: ghcr.io/moonshrd/telegramnftwizard
    restart: always
    volumes:
      - ".env:/app/.env"

  watchtower:
    image: containrrr/watchtower
    command: --interval 300 --include-stopped --include-restarting --cleanup
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.docker/config.json:/config.json